### ISSUE TITLE
Intégration Page Conseils 

### ISSUE THREAD

**Issue by ELBOUANANI10** [ELBOUANANI10/CORONA#4]
Convertissez le design graphique de la page Conseil en un code HTML CSS compressé et Compatible avec tous les navigateur en utilisant NPM, SASS.

Analysez bien le [Design](https://github.com/Youcodeteam/C2N3_C3N3/tree/master/Design)

Intégrez votre code html en respectant la structure que vous venez d’imaginer

Pensez bien à votre stratégie de découpage.

Nommez vos blocs de façon sémantique en utilisant le concept BEM

Incluez un [reset] ("https://necolas.github.io/normalize.css/") css dans le header de votre page html.

 Intégration section Informations

 Intégration section Symptômes

 Intégration Recommandations officielles

 Intégration section Hero Footer contenant la section Test et le footer

Notez Bien :

Cette peut être élaborer qu'avec du Flexbox, Css Grid et même sans média queries.

**Comment by imanegannaoui** [comment]
Tu n'as pas terminé la page conseil ?

**Comment by ELBOUANANI10** [comment]
j'ai des problémes au niveau de connexion internet je te l dis plusieurs fois mais aucun ne trouve une solution , d'autre coté le travail presque termine .

**Comment by imanegannaoui** [comment]
Essayez de faire un effort svp et de trouver une solution on compte sur toi,
le problème que tu es le seul qui est en retard dans la classe.

**Comment by ELBOUANANI10** [comment]
je fais le maximum imane, et qui consérne le retard c 'est la premiére fois qui je trouve ces problémes y a pas les bonnes moyennes .
j'attend des messages pour m'aider de trouver une solution pas ca  !!!!!!!!!

**Comment by ELBOUANANI10** [comment]
voilà le travail
