### ISSUE TITLE
Intégration Page Accueil 

### ISSUE THREAD

**Issue by ELBOUANANI10** [ELBOUANANI10/CORONA#5]
Convertissez le design graphique de la page d'accueil en un code HTML CSS compressé et Compatible avec tous les navigateur en utilisant NPM, SASS.

Analysez bien le Design

Intégrez votre code html en respectant la structure que vous venez d’imaginer

Pensez bien à votre stratégie de découpage.

Nommez vos blocs de façon sémantique en utilisant le concept BEM

Incluez un reset css dans le header de votre page html.

 Intégration section Hero Header contenant Menu , Warning Info, Illustration et son texte et Boutton Test

 Intégration section Symptômes

 Intégration Recommandations officielles

 Intégration section Hero Footer contenant la section Test et le footer

**Comment by imanegannaoui** [comment]
tu as terminé la page d'accueil ?

**Comment by ELBOUANANI10** [comment]
oui je termine la partie de page d'acceuil .
parfait
